# NumPy Array Reshaping, Resizing & Indexing - Commands Reference Guide

## Table of Contents
1. [Array Reshaping Methods](#array-reshaping)
2. [Indexing and Slicing Methods](#indexing-slicing)
3. [Utility Functions](#utilities)

## Array Reshaping Methods {#array-reshaping}

| Method | Syntax | Purpose | In-Place | Returns |
|--------|--------|---------|----------|---------|
| **reshape()** | `arr.reshape(new_shape)` | Change array shape without changing data | ❌ | View (if possible) |
| **ravel()** | `arr.ravel()` | Flatten array into 1D | ❌ | View |
| **flatten()** | `arr.flatten()` | Flatten array into 1D (always copy) | ❌ | Copy |
| **resize()** | `arr.resize(new_shape, refcheck=False)` | Resize array in-place (can change size) | ✅ | None |
| **squeeze()** | `np.squeeze(arr)` or `arr.squeeze()` | Remove axes of size 1 | ❌ | New array |

## Indexing and Slicing Methods {#indexing-slicing}

| Method | Syntax | Purpose | Example |
|--------|--------|---------|---------|
| **Basic Indexing** | `arr[index]` | Access element by position | `arr[0]` → first element |
| **Negative Indexing** | `arr[-1]` | Access from end | `arr[-1]` → last element |
| **Slicing (1D)** | `arr[start:stop:step]` | Extract range of elements | `arr[1:4]` → elements 1,2,3 |
| **Slice Omit** | `arr[:3]` or `arr[3:]` | Omit start or stop | `arr[:3]` → first 3 elements |
| **Reverse Slicing** | `arr[::-1]` | Reverse array | `arr[::-1]` → reversed array |
| **2D Indexing** | `arr[row, col]` | Access element in 2D array | `arr[0, 1]` → row 0, col 1 |
| **Column Selection** | `arr[:, col_idx]` | Extract entire column | `arr[:, 2]` → all rows, col 2 |
| **2D Slicing** | `arr[r1:r2, c1:c2]` | Extract submatrix | `arr[0:2, 1:]` → rows 0-1, cols 1+ |
| **Boolean Indexing** | `arr[arr > value]` | Filter by condition | `arr[arr > 15]` → elements > 15 |
| **Fancy Indexing** | `arr[indices_list]` | Select by index array | `arr[[0, 2, 4]]` → select indices 0,2,4 |
| **np.where()** | `np.where(condition)` | Find indices where condition is true | `np.where(arr > 20)` → indices where arr > 20 |

## Utility Functions {#utilities}

| Function | Purpose |
|----------|---------|
| `__array_interface__['data'][0]` | Get memory address of array data |
| `arr.shape` | Get dimensions of array |
| `np.where(condition)` | Find indices matching condition |

# Array Reshaping and resizing in numpy

###  1. reshape()

Change Shape Without Changing Data

##### Notes:
The total number of elements must remain the same.

reshape() returns a new view if possible (no copy).

You can use -1 to let NumPy infer one dimension:

### 2. ravel() 

Flatten into 1D (returns a view)

Fast and memory-efficient.

Changes reflect in the original array (if no copy made).

In [1]:
# Import NumPy library for array operations and reshaping
import numpy as np

In [2]:
# Create a 2D array (2 rows, 2 columns) for demonstration of reshape operations
a = np.array([[1, 2], [3, 4]])

In [3]:
# Check the shape attribute - returns tuple (2, 2) representing dimensions
a.shape

(2, 2)

In [4]:
# ravel() method - Flattens 2D array into 1D

# Returns a view (not a copy), so memory-efficientprint(a.ravel())

In [5]:
# Display the original 2D array to verify it hasn't changed yet
print(a)

[[1 2]
 [3 4]]


## Understanding id() vs __array_interface__['data'][0]

### Key Distinction: Python Object vs Underlying Data

**`id()` checks Python object identity** — whether two variables refer to the *same Python object container*

**`__array_interface__['data'][0]` checks data memory address** — whether two arrays point to the *same underlying data in RAM*

---

### Visual Representation

```
┌─────────────────────────────────────────────────────────────────────┐
│                      PYTHON VARIABLE SCOPE                           │
├─────────────────────────────────────────────────────────────────────┤
│                                                                       │
│  Variable: a                          Variable: a_ravel              │
│  ┌──────────────────┐                ┌──────────────────┐           │
│  │ Python Object A  │                │ Python Object B  │           │
│  │ id(a) = 46...    │                │ id(a_ravel) =... │           │
│  └────────┬─────────┘                └────────┬─────────┘           │
│           │                                    │                     │
│           └────────────────┬───────────────────┘                    │
│                            │                                        │
│                            ↓                                        │
│        ┌─────────────────────────────────────────┐                 │
│        │   MEMORY LEVEL (RAM)                     │                 │
│        │  __array_interface__['data'][0]          │                 │
│        │  Address: 0x7f8b8c0a0000                 │                 │
│        │                                           │                 │
│        │  ┌──────────────────────────────┐        │                 │
│        │  │ ACTUAL ARRAY DATA            │        │                 │
│        │  │ [11, 2, 3, 4]                │        │                 │
│        │  │                              │        │                 │
│        │  │ Both objects point HERE ✓   │        │                 │
│        │  └──────────────────────────────┘        │                 │
│        │                                           │                 │
│        └─────────────────────────────────────────┘                 │
│                                                                       │
└─────────────────────────────────────────────────────────────────────┘
```

### Key Points

| Aspect | id() | __array_interface__['data'][0] |
|--------|------|--------------------------------|
| **What it checks** | Python object identity | Raw data memory address |
| **For a and a_ravel** | ❌ DIFFERENT | ✅ SAME |
| **Meaning** | Separate Python objects | Share same underlying data |
| **Memory efficiency** | New container | No copy of data |
| **Changes reflected?** | N/A | YES - both see changes |

### Why This Matters

- **`ravel()` is memory-efficient** because it doesn't copy data (both objects point to same RAM)
- **Changes to one affect the other** because they share the same underlying data
- **But they're separate Python objects**, so `id()` returns different values
- **`flatten()` would be different** — creates both a new object AND new data (different memory address)

This demonstrates that NumPy views create a new object interface but reuse the underlying data!

In [8]:
# Store the flattened array and check memory addresses using id()
# id() returns the memory address of the object in Python
a_ravel = a.ravel()
print(a_ravel)
print(id(a))  # Memory address of original array
print(id(a.ravel()))  # Memory address of new ravel() call
print(id(a_ravel))  # Memory address of stored ravel() result

[1 2 3 4]
2144108406192
2144108406672
2144108406576


In [9]:
# __array_interface__['data'][0] attribute gives the actual memory address
# This is the address where the raw array data begins in memory
# Different from Python's id() which references the object container

In [10]:
# Print the memory address of the original array 'a' data
# This is where the actual array elements are stored in RAM
print(f"Data address of 'a': {a.__array_interface__['data'][0]}")

Data address of 'a': 2143543347760


In [11]:
# Print memory address of a.ravel() when called directly
# Shows that ravel() returns a view pointing to the same underlying data
print(f"Data address of a.ravel() directly: {a.ravel().__array_interface__['data'][0]}")

Data address of a.ravel() directly: 2143543347760


In [12]:
# Print memory address of the stored a_ravel variable
# Should be the same as original 'a' since ravel() returns a view, not a copy
print(f"Data address of 'a_ravel': {a_ravel.__array_interface__['data'][0]}")

Data address of 'a_ravel': 2143543347760


In [13]:
# Modify the original array - Change first element from 1 to 11
# Since ravel() returns a view, this will affect a_ravel as well
a[0][0] = 11

In [14]:
# Display array 'a' - notice first element is now 11
# This confirms the change we made
a

array([[11,  2],
       [ 3,  4]])

In [15]:
# Print memory address again after modification
# Address remains the same - data location hasn't changed, only the value
print(f"Data address of 'a': {a.__array_interface__['data'][0]}")

Data address of 'a': 2143543347760


In [16]:
# Display a_ravel - shows the change (11) at the beginning
# This proves that ravel() returns a VIEW, not a copy - changes are reflected
print(a_ravel)

[11  2  3  4]


### 3. flatten()

Flatten into 1D (returns a copy)

In [18]:
# Display the modified array 'a' (now with 11 as first element)
a

array([[11,  2],
       [ 3,  4]])

In [19]:
# flatten() method - Flattens array into 1D and returns a COPY (not a view)
# Unlike ravel(), changes to the flattened array don't affect the original
b = a.flatten()

In [20]:
# Compare memory addresses of 'a' and 'b' (flatten result)
# Different addresses confirm flatten() creates a COPY, not a view
print(f"Data address of 'a': {a.__array_interface__['data'][0]}")
print(f"Data address of 'b': {b.__array_interface__['data'][0]}")

Data address of 'a': 2143543347760
Data address of 'b': 2143543328464


In [21]:
# Display the flattened array 'b' as a 1D array
b

array([11,  2,  3,  4])

In [23]:
b[0] = 99  # Modify the first element of the flattened array 'b'
print(b)  # Display modified 'b' to show change (99 at the beginning)
print(a)  # Display 'a' to confirm it has NOT changed (still 11 at the beginning)

[99  2  3  4]
[[11  2]
 [ 3  4]]


### 4. resize()

Resize Array In-place

Unlike reshape(), it can change total size. Data may be truncated or padded with zeros.

In [24]:
# Create a 2x3 array to demonstrate reshape() vs resize()
a = np.array([[1, 2, 3], [4, 5, 6]])

In [25]:
# reshape() - Change shape from (2,3) to (3,3)
# This returns a NEW array with reshaped data, requires 9 elements but array has 6 - will cause error
a = a.reshape((3,3))

ValueError: cannot reshape array of size 6 into shape (3,3)

In [26]:
# Display result - this will show an error because reshape can't change total elements
a

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
# Recreate the 2x3 array for the resize() demonstration
a = np.array([[1, 2, 3], [4, 5, 6]])

In [28]:
# resize() - Resize array IN-PLACE to (3,3)
# Unlike reshape(), resize() can change the total size
# refcheck=False allows resizing even if the array is referenced by variables
a.resize((3,3), refcheck=False)  # In-place: means changing the data without reassignment

In [29]:
# Display resized array - now 3x3, with zeros padded for missing elements
a

array([[1, 2, 3],
       [4, 5, 6],
       [0, 0, 0]])

## Key Distinction: resize() vs reshape()

**`resize()` does NOT return a new array**

- **Returns**: `None` (not a new array)
- **Modifies**: Original array in-place
- **Data**: Does NOT copy — pads/truncates existing data
- **Assignment**: Do NOT assign result (there is none)

```python
a = np.array([[1, 2, 3], [4, 5, 6]])
a.resize((3,3), refcheck=False)  # Modifies 'a' directly, returns None
# a is now [[1, 2, 3], [4, 5, 6], [0, 0, 0]]
```

### Comparison Table

| Feature | reshape() | resize() |
|---------|-----------|----------|
| Returns | New array/view | None |
| Modifies original | ❌ No | ✅ Yes (in-place) |
| Copies data | ❌ No | ❌ No |
| Can change size | ❌ No | ✅ Yes |
| refcheck parameter | ❌ No | ✅ Yes |

**Note**: `refcheck=False` allows resizing even if the array is referenced elsewhere, preventing errors.

### 5. squeeze()

Remove single-dimensional axes

Useful for removing extra dimensions from image or model output shapes like (1, 28, 28, 1)

In [ ]:
# squeeze() - Remove axes of size 1 from array shape (1,3,1) → (3,)
# Useful for removing extra dimensions from image data, CNN outputs, etc.
a = np.array([[[1], [2], [3]]])
print(a.shape)  # Original shape (1, 3, 1)

(2, 3, 1)


In [ ]:
# Apply squeeze() to remove all single-dimensional axes
b = np.squeeze(a)

In [ ]:
# Display squeezed shape - now (3,) instead of (1,3,1)
print(b.shape)

(3,)


In [ ]:
# Display the squeezed array as a 1D array
b

array([1, 2, 3])

| Function        | Purpose                        | In-place | Returns Copy/View  |
| --------------- | ------------------------------ | -------- | ------------------ |
| `reshape()`     | Change shape (same size)       | ❌        | View (if possible) |
| `resize()`      | Resize array (can change size) | ✅        | None               |
| `ravel()`       | Flatten array (1D)             | ❌        | View               |
| `flatten()`     | Flatten array (1D)             | ❌        | Copy               |
| `squeeze()`     | Remove dimensions of size 1    | ❌        | New array          |


# Indexing and Slicing in NumPy — Beginner to Advanced

###  1. Basic Indexing (1D Arrays)

Slicing syntax: array[start:stop:step]

In [ ]:
# Create 1D array for basic indexing and slicing examples
arr = np.array([10, 20, 30, 40, 50])

In [ ]:
# Basic indexing - Access element at index 0 (first element)
print(arr[0])

10


In [ ]:
# Negative indexing - Access element from the end
# -1 is the last element, -2 is second-to-last, etc.
print(arr[-1])

50


In [ ]:
# Direct indexing - Access element at index 4 (fifth element)
print(arr[4])

50


In [ ]:
# Slicing - Extract range of elements: arr[start:stop:step]
# arr[1:4] returns elements at indices 1, 2, 3 (stop is exclusive)
# For arr = [10, 20, 30, 40, 50], this returns [20, 30, 40]
print(arr[1:4])

[20 30 40]


In [ ]:
# Slicing with negative indices - arr[1:-1] returns elements between index 1 and last
# Excludes first and last elements: [20, 30, 40]
print(arr[1:-1])

[20 30 40]


In [ ]:
# Slicing with explicit start and stop
# arr[0:3] returns elements at indices 0, 1, 2 (stop is exclusive)
# For arr = [10, 20, 30, 40, 50], this returns [10, 20, 30]
print(arr[0:3])

[10 20 30]


In [ ]:
# Omitting start index - defaults to 0
# arr[:3] is equivalent to arr[0:3], returns first 3 elements
print(arr[:3])

[10 20 30]


In [ ]:
# Slicing with step parameter: arr[start:stop:step]
# arr[0:5:2] returns every 2nd element from index 0 to 5 (exclusive)
# For arr = [10, 20, 30, 40, 50], this returns [10, 30, 50]
arr[0:5:2]

array([10, 30, 50])

In [ ]:
# Omitting start and stop, using step=2
# arr[::2] returns every 2nd element starting from the first
# Equivalent to arr[0:len(arr):2]
arr[::2]

array([10, 30, 50])

In [ ]:
# Reverse slicing - negative step reverses the array
# arr[::-1] returns array in reverse order, works for both NumPy arrays and Python lists
arr[::-1]

array([50, 40, 30, 20, 10])

In [ ]:
# Reverse slicing also works for Python lists
# [::-1] reverses the list
list_a = [1,2,3,4,5,6,7]
list_a[::-1]

[7, 6, 5, 4, 3, 2, 1]

### 2. Indexing in 2D Arrays

In [ ]:
# Create 2D array (3x3 matrix) for 2D indexing examples
mat = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

In [ ]:
# 2D indexing using nested brackets - Access element at row 0, column 1
# mat[0][1] returns 2 (first row, second column)
mat[0][1]

np.int64(2)

In [ ]:
# 2D indexing using comma notation - Preferred NumPy syntax
# mat[0, 1] is equivalent to mat[0][1], returns 2
# This is more efficient and readable
mat[0, 1]

np.int64(2)

In [ ]:
# Select entire column - mat[:, 2] returns all rows from column 2
# Returns [3, 6, 9] (third column)
# : means "all rows", 2 specifies the column index
mat[:, 2]

array([3, 6, 9])

In [ ]:
# 2D slicing - Extract a submatrix (rows 0-1, columns 1-2)
# mat[0:2, 1:] returns:
# [[2 3]
#  [5 6]]
mat[0:2, 1:]

array([[2, 3],
       [5, 6]])

In [ ]:
# 2D reverse slicing - Reverse both rows and columns
# mat[::-1, ::-1] reverses the matrix both horizontally and vertically
# Result:
# [[9 8 7]
#  [6 5 4]
#  [3 2 1]]
mat[::-1, ::-1]

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

### 3. Boolean Indexing

In [ ]:
# Create array for boolean indexing demonstration
arr = np.array([5, 10, 15, 20, 25])

In [ ]:
# Goal: Get all elements greater than 15 using boolean indexing (efficient NumPy way)

In [ ]:
# Traditional Python way - Use loop to find elements > 15 (slow for large arrays)
l = []
for i in arr:
    if i > 15:
        l.append(i)
l = np.array(l)
print(l)

[20 25]


In [ ]:
# Create a boolean mask - Returns array of True/False for each element
# arr > 15 returns [False, False, False, True, True]
arr > 15

array([False, False, False,  True,  True])

In [ ]:
# Boolean indexing - Use boolean mask to filter array
# arr[arr > 15] returns only elements where condition is True: [20, 25]
# Much faster than the traditional loop approach above
arr[arr > 15]

array([20, 25])

### 4. Fancy Indexing

In [ ]:
# Fancy indexing - Use array of indices to select specific elements
# arr[[0, 2, 4]] selects elements at indices 0, 2, 4
arr = np.array([100, 200, 300, 400, 500])
indices = [0, 2, 4]
print(arr[indices])  # Returns [100, 300, 500]

[100 300 500]


In [ ]:
# Create 2D array for 2D fancy indexing
mat = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

In [ ]:
# Boolean indexing on 2D array - Returns flattened array of elements > 5
# mat[mat>5] returns all elements greater than 5 in a 1D array: [6, 7, 8, 9]
mat[mat>5]

array([6, 7, 8, 9])

#

In [ ]:
# Advanced 2D fancy indexing - Select specific elements using parallel index arrays
# mat[[0,1], [2,2]] selects:
# [0, 2] → element at row 0, column 2 → 3
# [1, 2] → element at row 1, column 2 → 6
# Returns [3, 6]
mat[[0,1],
    [2,2]]

array([3, 6])

### 5. Modifying with Indexing

In [ ]:
# Modify array element using indexing - Change element at index 2 to 10
arr = np.array([1, 2, 3, 4])
arr[2] = 10
print(arr)  # Result: [1, 2, 10, 4]

[ 1  2 10  4]


In [ ]:
# Modify multiple elements using boolean indexing
# arr[arr > 2] = 100 sets all elements > 2 to 100
arr[arr > 2] = 100
print(arr)  # Result: [1, 2, 100, 100]

[  1   2 100 100]


### 6. Indexing with np.where()

In [ ]:
# Create array for np.where() demonstration
arr = np.array([10, 15, 20, 25, 30])

In [ ]:
# np.where(condition) - Returns indices where condition is True
# Find indices where arr > 20
idx = np.where(arr > 20)

In [ ]:
# Print the indices returned by np.where()
# Returns tuple of arrays with indices: (array([2, 3, 4]),)
# Indices 2, 3, 4 correspond to values 20, 25, 30 (all > 20)
print(idx)

(array([3, 4]),)


In [ ]:
# Use indices from np.where() to get the actual values
# arr[idx] returns the elements at the found indices: [20, 25, 30]
print(arr[idx])

[25 30]
