# NumPy Commands and Methods Reference Guide

## Table of Contents
1. [Array Creation Methods](#array-creation)
2. [Array Attributes](#array-attributes)
3. [Array Reshaping](#array-reshaping)
4. [Utilities](#utilities)

## Array Creation Methods {#array-creation}

| Command | Syntax | Purpose |
|---------|--------|---------|
| **np.array()** | `np.array(list, dtype=...)` | Convert Python list to NumPy array with optional data type specification |
| **np.arange()** | `np.arange(start, stop, step)` | Create array with evenly spaced values within interval (similar to Python's range) |
| **np.linspace()** | `np.linspace(start, stop, num=50)` | Create array with specified number of evenly spaced values (stop is inclusive) |
| **np.zeros()** | `np.zeros(shape, dtype=...)` | Create array filled with zeros with given shape |
| **np.ones()** | `np.ones(shape, dtype=...)` | Create array filled with ones with given shape |
| **np.full()** | `np.full(shape, fill_value)` | Create array filled with specified value |
| **np.eye()** | `np.eye(N, M=None)` | Create identity matrix (1s on diagonal, 0s elsewhere) |
| **np.empty()** | `np.empty(shape, dtype=...)` | Create uninitialized array (faster, contains random values) |
| **np.random.rand()** | `np.random.rand(d0, d1, ...)` | Create array with random values between 0 and 1 |

## Array Attributes {#array-attributes}

| Attribute | Purpose | Example |
|-----------|---------|---------|
| **shape** | Returns tuple of array shape | `arr.shape` → `(2, 3)` |
| **ndim** | Returns number of dimensions present in array | `arr.ndim` → `2` |
| **size** | Returns total number of elements | `arr.size` → `6` |
| **dtype** | Returns data type of array elements | `arr.dtype` → `dtype('int64')` |
| **itemsize** | Returns size in bytes of one element | `arr.itemsize` → `8` |
| **nbytes** | Returns total bytes consumed by array | `arr.nbytes` → `48` |
| **T** | Returns transpose of the array | `arr.T` returns transposed array |

## Array Reshaping {#array-reshaping}

| Method | Syntax | Purpose |
|--------|--------|---------|
| **reshape()** | `arr.reshape(new_shape)` | Change array shape without changing data; use -1 to infer dimension |

## Utilities {#utilities}

| Function | Purpose |
|----------|---------|
| **time.perf_counter()** | Returns high-resolution performance counter for benchmarking |

In [1]:
# Install numpy and pandas packages with system package override
#%pip install --break-system-packages numpy pandas

In [2]:
# Import time module for performance benchmarking
import time

In [3]:
# Demonstrate Python list performance for element-wise addition
# Create two lists with 1 million elements each
a = list(range(1000000))
b = list(range(1000000))

# Benchmark: Add two lists element-by-element using comprehension
# time.perf_counter() gives high-resolution time for precise benchmarking
start_p = time.perf_counter()
c = [x + y for x, y in zip(a, b)]  # Python list comprehension for addition
end_p = time.perf_counter()
total_p = end_p - start_p
print("Python:", total_p)  # Print execution time for Python lists

Python: 0.07255959999929473


In [4]:
# Import NumPy library for efficient numerical computing
import numpy as np

In [5]:
# Convert Python lists to NumPy arrays for optimized operations
a_np = np.array(a)
b_np = np.array(b)

# Benchmark: Add two NumPy arrays using vectorized operation
# NumPy operations are implemented in C and are much faster than Python loops
start_n = time.perf_counter()
c_np = a_np + b_np  # Vectorized addition (no explicit loop needed)
end_n = time.perf_counter()
total_n = end_n - start_n
print("NumPy:", total_n)  # Print execution time for NumPy arrays

NumPy: 0.0022473000008176314


In [6]:
# Compare performance: Calculate how many times faster NumPy is than Python
print(f"Numpy is faster than python by : {total_p/total_n:.2f}")  # Display speed improvement ratio

Numpy is faster than python by : 32.29


# Numpy

Python lists are : 
 - Flexible but slow for numerical operations
 - Not designed for matrix math or
 - Does not support vectorised operation
 - Are memory inefficient for large numerical data

Why use numpy?
- Fast than pure python for numerical computation
- Vectorized operation (no explicit loops)
- Broadcasting (operate on arrays of different shape)
- Memory efficient
- Comes with powerful linear algebra, random tools etc

Use of numpy :
- Scientific python

In [7]:
# Optional: Install numpy via pip (commented out, already imported above)
# !pip install numpy

In [8]:
# Re-import numpy for array creation examples
import numpy as np

# creating arrays in numpy

### 1. np.array()

In [9]:
# np.array() - Create a 1D NumPy array from a Python list
arr_1 = np.array([1,2,3])

print(arr_1)  # Display the array
print(type(arr_1))  # Verify it's a numpy.ndarray, not a Python list

[1 2 3]
<class 'numpy.ndarray'>


In [10]:
# Display the array arr_1 directly (returns the array representation)
arr_1

array([1, 2, 3])

In [11]:
# Check the data type of the first element in the array
# numpy.int64 is more memory-efficient than Python's default integer type
type(arr_1[0])

numpy.int64

In [12]:
# Create a 2D NumPy array (matrix) from nested lists
# This represents a 2x3 matrix (2 rows, 3 columns)
arr_2 = np.array([[1,2,3], [4,5,6]])

print(arr_2)  # Display the 2D array/matrix

[[1 2 3]
 [4 5 6]]


In [13]:
# Access the first row of the 2D array using indexing
# arr_2[0] returns the entire first row [1, 2, 3]
arr_2[0]

array([1, 2, 3])

In [14]:
# Access a specific element: row 0 (first row), column 2 (third element)
# Returns 3 from the array [[1,2,3], [4,5,6]]
arr_2[0][2]

np.int64(3)

In [15]:
# Access a specific element: row 1 (second row), column 2 (third element)
# Returns 6 from the array [[1,2,3], [4,5,6]]
arr_2[1][2]

np.int64(6)

In [16]:
# Important: Arrays can contain only one data type
# NumPy will convert all elements to their common data type (here: string)
arr_3 = np.array([1,2,3, "hello"])

print(arr_3)  # All elements converted to strings
print(type(arr_3))  # Still a numpy.ndarray

['1' '2' '3' 'hello']
<class 'numpy.ndarray'>


In [17]:
# Verify that mixed data types are converted to string type
# The element '1' is now a numpy string, not an integer
print(type(arr_3[1]))

<class 'numpy.str_'>


In [18]:
# Specify explicit data type using dtype parameter
# np.int8: 8-bit integer (-128 to 127) - more memory efficient than int64
arr_4 = np.array([1,2,3], dtype=np.int8)
print(type(arr_4))  # Still numpy.ndarray

<class 'numpy.ndarray'>


In [19]:
# Verify the data type of individual elements - confirms int8 dtype
type(arr_4[0])

numpy.int8

In [20]:
# Attempt to convert mixed types to float16 - "hello" cannot be converted
# This will raise an error as strings cannot be cast to float16
arr_5 = np.array([1,2,3, "hello"], dtype=np.float16)

ValueError: could not convert string to float: 'hello'

In [21]:
# Try converting numeric string to float16
# "10" is a string but can be successfully converted to float16
arr_6 = np.array([1,2,3, "10"], dtype=np.float16)

In [22]:
# Display the arr_6 array with float16 values
arr_6

array([ 1.,  2.,  3., 10.], dtype=float16)

In [23]:
# Important Note: NumPy arrays can only contain elements of a single data type
# Mixed types are automatically converted to a common type

### 2. np.arange(start, stop, step)

In [24]:
# Compare Python's range() function (returns list)
# Python range: range(start, stop, step) - similar to np.arange()
list(range(1, 11, 2))  # Returns [1, 3, 5, 7, 9]

[1, 3, 5, 7, 9]

In [25]:
# np.arange(start, stop, step) - Creates NumPy array with evenly spaced values
# Similar to Python's range() but returns NumPy array
# start=1, stop=11 (exclusive), step=2
b = np.arange(1, 11, 2)

In [26]:
# Display the array created with np.arange()
b  # Shows [1 3 5 7 9]

array([1, 3, 5, 7, 9])

### 3. np.linspace(start, stop, num=x)
stop - inclusive

In [27]:
# np.linspace(start, stop, num) - Creates array with specified number of evenly spaced values
# Key difference: stop is INCLUSIVE (opposite of arange)
# start=1, stop=100, num=4 equally spaces between 1 and 100
np_linspace_1 = np.linspace(1,100,4)
print(np_linspace_1)  # [1.0, 33.666..., 66.333..., 100.0]
print(type(np_linspace_1))  # numpy.ndarray

[  1.  34.  67. 100.]
<class 'numpy.ndarray'>


In [28]:
# Another linspace example: 10 values between 1 and 10
np_linspace_2 = np.linspace(1,10,10)
print(np_linspace_2)  # Returns 10 evenly spaced values from 1 to 10
print(type(np_linspace_2))  # numpy.ndarray

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
<class 'numpy.ndarray'>


In [29]:
# Iterate through linspace array elements
# Elements are stored as float64 by default in linspace
for num in np.linspace(1,10,10):
    # print(type(num))
    print(num)  # Print each value
    # print(type(int(num)))
    # print("=================")

1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0
10.0


In [30]:
# Create linspace with dtype specified as int8 (8-bit integers)
# Values will be automatically converted to int8 type
for num in np.linspace(1,10,10, dtype=np.int8):
    print(num)  # Values truncated to integers

1
2
3
4
5
6
7
8
9
10


### 4. np.zeros(shape)

shape -> shape of matrix

In [31]:
# np.zeros(shape) - Create array filled with zeros
# shape: single integer for 1D array
npz_1 = np.zeros(5)  # Creates 1D array with 5 zeros

In [32]:
# Display the array of zeros (default dtype is float64)
npz_1

array([0., 0., 0., 0., 0.])

In [33]:
# Create 2D zero array with shape (5, 5) and dtype int8
# shape: tuple (rows, columns) for 2D array
npz_2 = np.zeros((5,5), dtype=np.int8)
print(npz_2)  # 5x5 matrix of zeros

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [34]:
# Create 2D zero array without specifying dtype (default is float64)
npz_2 = np.zeros((5,5))
print(npz_2)  # 5x5 matrix of float zeros

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [35]:
# Create 3D zero array with shape (5, 5, 5)
# shape: tuple (depth, rows, columns) for 3D array
npz_3 = np.zeros((5,5,5)) # take 5*5 and repeat it 5 times to create a 3D array (cube) of zeros
print(npz_3)  # 3D array (cube) of zeros

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [36]:
# ndarray.ndim - Returns the number of dimensions of the array
# npz_3 has 3 dimensions (depth, rows, columns)
npz_3.ndim

3

### 5. np.ones(shape)

shape -> shape of matrix

In [37]:
# np.ones(shape) - Create array filled with ones
# Similar to zeros but fills with 1.0 instead
npo_1 = np.ones((2,3))  # 2x3 matrix of ones
print(npo_1)

[[1. 1. 1.]
 [1. 1. 1.]]


### 6. np.full(shape, fill_value)

shape -> shape of matrix

In [38]:
# np.full(shape, fill_value) - Create array filled with a specific value
# shape: tuple of dimensions, fill_value: the value to fill all elements
npf_1 = np.full((2,3), 10)  # 2x3 matrix filled with value 10
print(npf_1)

[[10 10 10]
 [10 10 10]]


### 7. np.eye(shape)

shape -> shape of matrix

- does not exist in 1D
- min of 2D,shape

In [39]:
# np.eye(N, M) - Create identity matrix
# N: number of rows, M: number of columns (optional)
# Identity matrix has 1s on diagonal, 0s elsewhere
np.eye(3)  # 3x3 identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [40]:
# Eye matrix with M < N: 2 rows, 3 columns
# Identity matrix with fewer columns than rows
np.eye(2,3)  # 2x3 matrix with 1s on diagonal where possible

array([[1., 0., 0.],
       [0., 1., 0.]])

In [41]:
# Eye matrix with M > N: 3 rows, 2 columns
# Identity matrix with fewer columns than rows
np.eye(3,2)  # 3x2 matrix with 1s on diagonal where possible

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [42]:
# Eye matrix: 7x7 identity matrix
# All 1s on main diagonal, 0s everywhere else
np.eye(7,7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

### 8. np.empty(shape)

In [43]:
# np.empty(shape) - Create uninitialized array
# Contains arbitrary values (garbage data), very fast to create
# Useful when you'll fill the array immediately after creation
np.empty((2,2), dtype=np.int8)  # 2x2 array with random int8 values

array([[1, 1],
       [1, 1]], dtype=int8)

In [44]:
# Create empty array with float16 dtype
# Contains arbitrary floating-point values
np.empty((2,2), dtype=np.float16)  # 2x2 array with random float16 values

array([[0.   , 0.   ],
       [0.   , 1.984]], dtype=float16)

In [45]:
# Benchmark: Time np.empty() creation
# np.empty() is very fast because it doesn't initialize values
start_e = time.perf_counter()
np.empty((5,5))
end_e = time.perf_counter()
total_e = end_e - start_e
print(total_e)  # Display time taken

9.140000111074187e-05


In [46]:
# Benchmark: Time np.ones() creation
# np.ones() is slower because it initializes all values to 1
start_we = time.perf_counter()
np.ones((5,5))
end_we = time.perf_counter()
total_we = end_we - start_we
print(total_we)  # Display time taken (should be slower than empty)

0.00011850000009872019


### 9. np.random.rand(shape)

random values between 0 and 1

- Use: ML weights random initialization

In [47]:
# np.random.rand(shape) - Create array with random values between 0 and 1
# Used for random weight initialization in machine learning
# Returns uniform distribution values in [0, 1)
np.random.rand(2,8)  # 2x8 matrix of random values

array([[0.50075688, 0.34128575, 0.56617029, 0.80442955, 0.16013605,
        0.48049813, 0.16821112, 0.71829355],
       [0.17888201, 0.69422625, 0.49185803, 0.97374204, 0.63984771,
        0.44692316, 0.44929307, 0.92809062]])

In [48]:
# 1 D --> vector

# Numpy Array attributes

### 1. ndarray.shape

In [49]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print(arr.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


### 2. ndarray.ndim

In [50]:
print(arr.ndim)

2


### 3. ndarray.size

Returns the total number of elements in the array.

In [51]:
print(arr.size)

6


### 4. ndarray.dtype

Tells the data type of the array elements.

In [52]:
print(arr.dtype)

int64


### 5. ndarray.itemsize

Returns the size in bytes of one element.

1 byte --> 8 bit

int8 --> 8 bit

int64 --> int8 * 8 --> int64

In [53]:
print(arr.itemsize)

8


### 6. ndarray.nbytes
Total number of bytes consumed by the array.

In [54]:
print(arr.nbytes)

48


### 7. ndarray.T

Returns the transpose of the array.

In [55]:
print(arr) # 2 rows, 3 column

[[1 2 3]
 [4 5 6]]


In [56]:
print(arr.T)

[[1 4]
 [2 5]
 [3 6]]


# Array Reshaping and resizing in numpy

###  1. reshape()

Change Shape Without Changing Data

##### Notes:
The total number of elements must remain the same.

reshape() returns a new view if possible (no copy).

You can use -1 to let NumPy infer one dimension:

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])
print(arr.shape) # one dimensional array with 6 elements, its like a vector with six rows and 1 column

(6,)


In [59]:
# 2x3
# 3X2
# 4x2 -> No
# 6x1 -> Yes

In [60]:
reshaped_1 = arr.reshape(2, 3)
print(reshaped_1)

[[1 2 3]
 [4 5 6]]


In [61]:
reshaped_2 = arr.reshape(3, 2)
print(reshaped_2)

[[1 2]
 [3 4]
 [5 6]]


In [63]:
reshaped_2 = arr.reshape(1, 6)
print(reshaped_2)
print(reshaped_2.ndim)
print(reshaped_2.shape)

[[1 2 3 4 5 6]]
2
(1, 6)


In [65]:
arr = np.array([1, 2, 3, 4, 5, 6, 56, 100, 789])
print(arr.shape)

(9,)


In [66]:
reshaped_3 = arr.reshape(3, -1)
print(reshaped_3.shape)


(3, 3)


In [67]:
reshaped_3 = arr.reshape(-1, 3)
print(reshaped_3.shape)


(3, 3)


In [68]:
reshaped_3 = arr.reshape(2, -1)
print(reshaped_3.shape)


ValueError: cannot reshape array of size 9 into shape (2,newaxis)