Vectorization gives the CPU the ability to do parallel procesing

# NumPy Advanced Operations - Commands Reference Guide

## Table of Contents
1. [Array Operations](#array-operations)
2. [Aggregation Functions](#aggregation-functions)
3. [Sort/Search/Count Functions](#sort-search-count)
4. [Array Iteration](#iteration)
5. [Copy vs View vs Reference](#copy-view-reference)
6. [Stacking Operations](#stacking)
7. [String/Character Operations](#string-operations)

## Array Operations {#array-operations}

| Operation | Syntax | Purpose | Returns |
|-----------|--------|---------|---------|
| **Element-wise Addition** | `arr1 + arr2` | Add corresponding elements | Array |
| **Element-wise Multiplication** | `arr1 * arr2` | Multiply corresponding elements | Array |
| **Dot Product (1D)** | `np.dot(arr1, arr2)` | Multiply + sum elements | Scalar |
| **Matrix Multiplication (2D)** | `np.dot(mat1, mat2.T)` or `mat1 @ mat2.T` | Linear algebra multiplication | Matrix |
| **Transpose** | `arr.T` | Swap rows and columns | Array |

## Aggregation Functions {#aggregation-functions}

| Function | Syntax | Purpose | Returns |
|----------|--------|---------|---------|
| **sum()** | `np.sum(arr, axis=None)` | Sum all/axis elements | Scalar/Array |
| **min()** | `np.min(arr)` | Find minimum value | Scalar |
| **max()** | `np.max(arr)` | Find maximum value | Scalar |
| **argmin()** | `np.argmin(arr)` | Index of minimum | Index |
| **argmax()** | `np.argmax(arr)` | Index of maximum | Index |
| **mean()** | `np.mean(arr, axis=None)` | Average of elements | Scalar/Array |
| **std()** | `np.std(arr, axis=None)` | Standard deviation | Scalar/Array |
| **var()** | `np.var(arr, axis=None)` | Variance | Scalar/Array |
| **cumsum()** | `np.cumsum(arr)` | Cumulative sum | Array |
| **median()** | `np.median(arr, axis=None)` | Median value | Scalar/Array |
| **percentile()** | `np.percentile(arr, q)` | q-th percentile | Scalar/Array |

**Axis Parameter**: axis=0 (sum rows, keep cols), axis=1 (sum cols, keep rows), axis=None (global)

## Sort/Search/Count Functions {#sort-search-count}

| Function | Syntax | Purpose | Returns |
|----------|--------|---------|---------|
| **sort()** | `np.sort(arr)` | Sort array in ascending order | Sorted array |
| **argsort()** | `np.argsort(arr)` | Indices that would sort array | Index array |
| **searchsorted()** | `np.searchsorted(sorted_arr, val)` | Find insertion position | Index |
| **unique()** | `np.unique(arr)` | Find unique elements | Unique array |
| **bincount()** | `np.bincount(arr)` | Count frequency of each value | Count array |

## Array Iteration {#iteration}

| Method | Syntax | Purpose | Returns |
|--------|--------|---------|---------|
| **for loop (1D)** | `for x in arr:` | Iterate through elements | Element |
| **for loop (2D)** | `for row in arr_2d:` | Iterate through rows | Row (1D array) |
| **nditer()** | `for x in np.nditer(arr):` | Iterate all elements (any dims) | Scalar element |

## Copy vs View vs Reference {#copy-view-reference}

| Concept | Syntax | Memory | Changes Reflected | Use Case |
|---------|--------|--------|-------------------|----------|
| **Reference** | `b = a` | Same object, same data | ✅ Both see changes | Aliasing (not recommended) |
| **View** | `b = a.view()` | Different object, same data | ✅ Both see changes | Memory efficient, linked arrays |
| **Copy** | `b = a.copy()` | Different object, different data | ❌ Independent | Safe modifications |

**Check**: `np.shares_memory(a, b)` returns True for view/reference, False for copy

## Stacking Operations {#stacking}

| Function | Syntax | Purpose | Result |
|----------|--------|---------|--------|
| **vstack()** | `np.vstack((arr1, arr2))` | Stack arrays row-wise (vertically) | Taller array |
| **hstack()** | `np.hstack((arr1, arr2))` | Stack arrays column-wise (horizontally) | Wider array |

## String/Character Operations {#string-operations}

| Function | Syntax | Purpose | Returns |
|----------|--------|---------|---------|
| **np.char.add()** | `np.char.add(arr1, arr2)` | Concatenate strings | String array |
| **np.char.multiply()** | `np.char.multiply(arr, n)` | Repeat strings n times | String array |
| **np.char.upper()** | `np.char.upper(arr)` | Convert to uppercase | String array |
| **np.char.lower()** | `np.char.lower(arr)` | Convert to lowercase | String array |
| **np.char.capitalize()** | `np.char.capitalize(arr)` | Capitalize first letter | String array |
| **np.char.center()** | `np.char.center(arr, width, fillchar)` | Center string in field | String array |
| **np.char.replace()** | `np.char.replace(arr, old, new)` | Replace substring | String array |
| **np.char.split()** | `np.char.split(arr, sep)` | Split string by separator | Array of lists |
| **np.char.find()** | `np.char.find(arr, substring)` | Find index of substring | Index array |
| **np.char.count()** | `np.char.count(arr, substring)` | Count substring occurrences | Count array |

## Key Notes

- **Broadcasting**: Operations automatically expand dimensions when needed
- **In-place operations**: Some methods modify original array (check documentation)
- **Memory efficiency**: Views are faster than copies for large arrays
- **Axis indexing**: Always specify axis for multi-dimensional operations


In [6]:
# Import NumPy library for advanced numerical computing
# Alias 'np' is standard convention - all numpy functions accessed via np.function_name()
import numpy as np

In [7]:
# Create two Python lists and demonstrate list concatenation
# In Python, + operator concatenates lists (not element-wise like NumPy)
# Result: [1, 2, 3, 4, 5, 6] - lists are joined end-to-end
a_list = [1,2,3]
b_list = [4,5,6]

print(a_list + b_list)

[1, 2, 3, 4, 5, 6]


In [8]:
# Create 1D NumPy arrays for element-wise operations
# NumPy enables vectorized operations (faster than Python loops)
# + operator performs element-wise addition (not concatenation like lists)
# Result: [1+4, 2+5, 3+6] = [5, 7, 9]
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a+b)

[5 7 9]


In [ ]:
# Element-wise multiplication (Hadamard product) - multiply corresponding elements
# * operator is element-wise, NOT matrix multiplication
# Result: [1*4, 2*5, 3*6] = [4, 10, 18]
# For marix multiplication, the column of first matrix must match the row of second matrix
# Here the arraysa are 1D and the corresponding dimensions are 1*3 and 1*3, so the column of first array is not matching with the row of second array
# Internally what happens in dot product for arrays is, the second array is transposed first and then both the arrays are multiplied 
a*b

array([ 4, 10, 18])

In [10]:
# Dot product - multiply element-wise THEN sum the results
# np.dot(a, b) = (1*4) + (2*5) + (3*6) = 4 + 10 + 18 = 32
# Used in: machine learning, physics, linear algebra
print(np.dot(a,b))

32


In [11]:
# Create 2D arrays (matrices with 2 rows, 3 columns) for matrix operations
# Both have same shape (2, 3) - needed for element-wise operations
a_1 = np.array([[1,2,3],[4,5,6]])
b_1 = np.array([[1,2,3],[4,5,6]])

In [12]:
# Check dimensions of both matrices using .shape attribute
# Returns: tuple (rows, columns) e.g., (2, 3) means 2 rows, 3 columns
# .shape is critical for debugging matrix operations
print(a_1.shape)
print(b_1.shape)

(2, 3)
(2, 3)


In [23]:
# Matrix multiplication using np.dot()
# Formula: A (2x3) @ B^T (3x2) = Result (2x2)
# Note: b_1.T transposes - swaps rows/columns so shapes align for multiplication
# (2,3) @ (3,2) = (2,2) valid for multiplication
print(b_1.T) # Check shape of transposed matrix
np.dot(a_1, b_1.T)

[[1 4]
 [2 5]
 [3 6]]


array([[14, 32],
       [32, 77]])

In [14]:
# Matrix multiplication using @ operator (Python 3.5+)
# @ is shorthand for np.dot() - cleaner syntax for matrix operations
# Equivalent to: np.dot(a_1, b_1.T)
a_1@b_1.T

array([[14, 32],
       [32, 77]])

In [15]:
# Real-world example: Store inventory sold per product
# Products: apple, banana, smartphone, toy, furniture
# Data: Sales from 2 states (regions/stores)
# Shape (2,5): 2 states, 5 products - each element = quantity sold
shop_sold_amazon = np.array([
    [100, 200, 20, 30, 5], # state-1-product-sold
    [200, 400, 40, 60, 10] # state-2-product-sold
])
print(shop_sold_amazon.shape)

(2, 5)


In [16]:
# Product prices per state/region
# Data: Price of each product for each state (prices may vary by region)
# Shape (2,5): 2 states, 5 products - each element = unit price
# Note: Prices vary by state (e.g., apple: 30 state-1 vs 34 state-2)
price_amazon = np.array([
    [30, 10, 1000, 10, 200], # state-1-price
    [34, 12, 1100, 11, 220] # state-2-price
])
print(price_amazon.shape)

(2, 5)


In [17]:
price_amazon.T

array([[  30,   34],
       [  10,   12],
       [1000, 1100],
       [  10,   11],
       [ 200,  220]])

In [18]:
sales = np.dot(shop_sold_amazon, price_amazon.T)

In [19]:
sales

# [[state_1(price_of_state_1), state_1(price_of_state_2)]
# [state_2(price_of_state_1), state_2(price_of_state_2)]]

array([[26300, 29230],
       [52600, 58460]])

In [20]:
diag = np.eye(2)
print(diag)

[[1. 0.]
 [0. 1.]]


In [34]:
np.sum(sales*diag)

np.float64(84760.0)

# Aggregation function

In [35]:
a_2 = np.array([1,2,3,4,5])

In [36]:
np.sum(a_2)

np.int64(15)

In [37]:
np.min(a_2)

np.int64(1)

In [ ]:
np.max(a_2)

np.int64(5)

In [ ]:
# [1,2,3,4,5]
a_3 = [1,2,100, 45, 450, 2, 5]
np.argmax(a_3) # index of the max element # not aggresation function

np.int64(4)

In [57]:
np.argmin(a_3)

np.int64(0)

In [51]:
price_amazon = np.array([
    [30, 10, 1000, 10, 200], # state-1-price
    [34, 12, 1100, 11, 220], # state-2-price,
    [34, 12, 1100, 11, 220]
])

In [43]:
np.sum(price_amazon)

np.int64(2627)

In [ ]:
# Sum with axis=0: Sum across rows (down), keeping columns separate
# Returns one value per column - "total sales per product"
# For shop_sold_amazon: [100+200, 200+400, 20+40, ...] = total per product
np.sum(price_amazon, axis=0)
# axis->0 means sum over rows, keep columns

array([  64,   22, 2100,   21,  420])

In [ ]:
# Sum with axis=1: Sum across columns (right), keeping rows separate
# Returns one value per row - "total sales per state"
# For shop_sold_amazon: [100+200+20+30+5, 200+400+40+60+10] = total per state
np.sum(price_amazon, axis=1)
# axis->1 means sum over columns, keep rows

array([1250, 1377])

In [46]:
np.mean(a_3)

np.float64(86.42857142857143)

In [47]:
np.mean(price_amazon)

np.float64(262.7)

In [ ]:
np.mean(price_amazon, axis=1)

array([250. , 275.4])

In [ ]:
np.std(price_amazon, axis=1)

array([381.73289091, 419.66539052, 419.66539052])

In [58]:
np.var(price_amazon, axis=1)

array([145720.  , 176119.04, 176119.04])

In [53]:
np.cumsum([1,2,4,5,6,100])

array([  1,   3,   7,  12,  18, 118])

In [56]:
np.median(price_amazon, axis=1)

array([30., 34., 34.])

In [60]:
data = np.array([1, 3, 5, 7, 9])
print(np.percentile(data, 50))

5.0


# sort, search, counting functions

In [ ]:
arr = np.array([3, 6, 1, 1, 1, 1, 8, 2, 5, 6])

In [64]:
len(arr)

10

In [ ]:
# Sort array and get sorted indices
# np.sort(arr) - returns sorted values
# np.argsort(arr) - returns INDICES that would sort the array
# argsort() is powerful: use returned indices to sort other arrays the same way
print("Sorted:", np.sort(arr))
print("Sorted indices:", np.argsort(arr))
# Instead of returning the sorted values themselves, 
# it returns an array of indices that, when used to index the original array, would produce a sorted sequence.

Sorted: [1 1 1 1 2 3 5 6 6 8]
Sorted indices: [3 2 5 4 7 0 8 1 9 6]


In [ ]:
# Search, unique, and count operations
# np.searchsorted() - find insertion position for value in sorted array
# np.unique() - get all unique (distinct) elements from array
# np.bincount() - count frequency of each integer from 0 to max value
# Returns count array where index = value, element = count
print("Insert 4 position:", np.searchsorted(np.sort(arr), 4))
print("Unique elements:", np.unique(arr))
print("Count of each element:", np.bincount(arr)) # MIN - 0 , maX - 8

# 0,1,2,3,4,5,6,7,8
# 0,4,1....

Insert 4 position: 6
Unique elements: [1 2 3 5 6 8]
Count of each element: [0 4 1 1 0 1 2 0 1]


In [68]:
arr_new = np.array([3, 6, 1, 1, 1, 1, 1.2, 8, 2, 5, 6])

In [70]:
arr_new

array([3. , 6. , 1. , 1. , 1. , 1. , 1.2, 8. , 2. , 5. , 6. ])

In [ ]:
print("Count of each element:", np.bincount(arr_new), rul)

TypeError: Cannot cast array data from dtype('float64') to dtype('int64') according to the rule 'safe'

In [ ]:
# Standard for loop - simple iteration through elements
# Works for 1D arrays - each iteration gives one element
# For 2D arrays, for loop gives rows, not individual elements
arr = np.array([1, 2, 3, 4])
for x in arr:
    print(x)

1
2
3
4


In [75]:
arr_2d = np.array([[1, 2], [3, 4]])

for x in arr_2d:
    print(x)

[1 2]
[3 4]


In [77]:
list(range(0,11))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
np.arange(8)
# 2,4
# 1,8
# 2,2,2
# 2,6 (BEST)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [81]:
arr = np.arange(8).reshape(2,2,2)
arr

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
arr.ndim # attibute of the class

3

In [83]:
for i in arr:
    print(i)

[[0 1]
 [2 3]]
[[4 5]
 [6 7]]


In [ ]:
# Advanced iteration - iterate through individual SCALAR elements
# np.nditer() works for arrays of any dimension
# Automatically traverses all elements one by one (helpful for multi-dim arrays)
# Each iteration returns actual scalar value (not array)
for x in np.nditer(arr):
    print(x)

0
1
2
3
4
5
6
7


In [ ]:
# Create a reference assignment - NOT a copy
# b = a means: b and a point to THE SAME object in memory
# Changes to either will affect both (no data safety)
a = np.array([1, 2, 3])
b = a

In [ ]:
# Create a deep copy - independent array with copied data
# b = a.copy() creates a NEW array with COPIED data
# Changes to b don't affect a, and vice versa
# Memory usage: Higher (two copies of data), but safe
b = a.copy()

In [88]:
print(id(a))
print(id(b))

2116798518768
2116798518768


In [89]:
b[0] = 100

In [90]:
print(a)

[100   2   3]


In [91]:
b = a.copy()

In [92]:
print(id(a))
print(id(b))

2116798518768
2117406015184


In [ ]:
# Create a view - different Python object, SAME underlying data
# b = a.view() creates a NEW object that references SAME data as a
# Changes to values affect both objects (data is shared)
# Memory efficient: No data copy, but objects are linked
a = np.array([1, 2, 3,])

b = a.view()

In [95]:
print(id(a))
print(id(b))

2117413010000
2117413010480


In [96]:
print(np.shares_memory(a, b))

True


In [ ]:
# Stacking operations - combine multiple arrays into single array
# vstack (vertical stack) - stack arrays on top of each other (increase rows)
# hstack (horizontal stack) - stack arrays side by side (increase columns)

a = np.array([[1,2]])
b = np.array([[3,4]])

In [98]:
print(np.vstack((a,b)))

[[1 2]
 [3 4]]


In [99]:
print(np.hstack((a,b)))

[[1 2 3 4]]


# numpy char and strings

In [100]:
# np.char.<function_name>()

In [ ]:
# String addition using np.char.add() - concatenates strings
# Different from numeric addition (which adds numbers)
# Combines each element from arr1 with corresponding element from arr2
# Result: ['hello_user', 'world_123']
a = np.array(['hello', 'world'])
b = np.array(['_user', '_123'])

print(np.char.add(a, b))

['hello_user' 'world_123']


In [ ]:
# Repeat/multiply strings - repeats each string n times
# np.char.multiply(arr, n) where n is repetition count
# Result: ['hellohello', 'worldworld'] (each string repeated 2 times)
print(np.char.multiply(a, 2))

['hellohello' 'worldworld']


In [ ]:
# Case conversion operations on string arrays
# np.char.upper() - convert all to UPPERCASE
# np.char.lower() - convert all to lowercase
# np.char.capitalize() - capitalize first letter only
a = np.array(['hello', 'WORLD'])

print(np.char.upper(a)) 
print(np.char.lower(a)) 
print(np.char.capitalize(a))

['HELLO' 'WORLD']
['hello' 'world']
['Hello' 'World']


In [107]:
# np.char.center()

print(np.char.center(a, 11, fillchar='*'))

['***hello***' '***WORLD***']


In [130]:
def password(value):
    # print(value[-4:])
    p = np.array([value[-4:]])
    print(p)
    print(np.char.center(p, 30, fillchar='*'))

In [131]:
password("canwedoitlaterpass")

['pass']
['*************pass*************']


In [132]:
# np.char.replace()
a = np.array(['data_science', 'machine_learning'])

print(np.char.replace(a, '_', ' '))

['data science' 'machine learning']


In [133]:
# np.char.split()

print(np.char.split(a, sep='_'))

[list(['data', 'science']) list(['machine', 'learning'])]


In [ ]:
# np.char.find() / np.char.count()
print(np.char.find(a, 'learn')) 
# ['data_science', 'machine_learning']

[-1  8]


In [135]:
print(np.char.count(a, 'a'))
print(np.char.count(a, 'data'))

[2 2]
[1 0]


# NUMPY COMPLETED